### PR TITLE
Fix handling tags namespaces

### PR DESCRIPTION
**Pull request by Michsior14**
The PR fixes missing tag namespaces in generated HTML and resolve problems with [Angular SVG namespaces](https://teropa.info/blog/2016/12/12/graphics-in-angular-2.html).

### CODE REVIEW

**Comment by Michsior14** [comment]
The tests failed on Travis because of missing snapshots. As far I see, the problem has already existed on the master.

**Comment by StarpTech** [comment]
Hi @Michsior14 thanks for contribution.

This use case shouldn't be covered by an formatter.
The user should be aware of that behaviour as described in your link when they split their svg in multiple components.

Another thing is that this change will break the normal `SVG` tests because on every svg element, a `svg` prefix is added even when no one was defined explicitly e.g

```html
<svg>
  <g></g>
</svg>
```
output
```html
<svg>
  <svg:g></g>
</svg>
```

> The tests failed on Travis because of missing snapshots. As far I see, the problem has already existed on the master.

Tests are working locally but it seems there is an issue with snapshots and CI https://github.com/facebook/jest/issues/7094

**Comment by Michsior14** [comment]
Ahh, yep you are right regarding adding the prefix when is not necessary. But nevertheless, the situation when you have 
`<svg:g></svg:g>`
in the template it should be preserved not changed to 
`<g></g>`
as it is right now. Do you have an idea how to achieve this?

**Comment by StarpTech** [comment]
Thanks for the example and now I understand your issue. We have to store that information in the AST node. I will provide a fix.

**Comment by StarpTech** [comment]
The issue was fixed in https://github.com/Prettyhtml/prettyhtml/pull/34

**Comment by StarpTech** [comment]
@Michsior14 Issue was fixed with prettyhtml 0.1.8

**Pull request closed without merging**
